version: '3'
services:
  mongodb-primary:
    image: bitnami/mongodb
    ports:
      - 27017:27017
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ADVERTISED_HOSTNAME: localhost
      MONGODB_ROOT_USERNAME: root
      MONGODB_ROOT_PASSWORD: example
      MONGODB_REPLICA_SET_KEY: replicaSetKey
      MONGODB_REPLICA_SET_NAME: rs0